### ISSUE TITLE
Error: SQLSTATE=22504 SQLCODE=-191

### ISSUE THREAD

**Issue by patrickhrastnik** [IBM/nodejs-idb-connector#129]
**Please complete the following information:**
- Node.js version: v12.16.1
- idb-connector version: 1.2.9
- idb-pconnector version: 1.0.8
- IBM i version: V7R3M0

**Describe the bug**

When I try to run an Sql Insert Statement, I get either of these Error Codes.
- Error: SQLSTATE=58004 SQLCODE=-901 ("UNSUCCESSFUL EXECUTION CAUSED BY A SYSTEM ERROR THAT DOES NOT PRECLUDE THE SUCCESSFUL EXECUTION OF SUBSEQUENT SQL STATEMENTS")
- Error: SQLSTATE=22504 SQLCODE=-191 ("A STRING CANNOT BE USED BECAUSE IT IS INVALID MIXED DATA")

I try to insert data into an Sql defined table with a CLOB field.

The funny thing is, some months ago (when I implemeted the feature which is now broken), the statement performed without any issues. Now I get the same behavior on both of our IBM i machines.
I think the error might origin in our environment or runtime - I just don't understand the error. Hopefully someone of you can help me figure it out.

**To Reproduce**

Sql Table definition:
```sql
create or replace table holog.HOLOJP (
  subjjl char(64) not null default '',
  lomejl clob not null default ''
)
rcdfmt holojlf0;
```
node.js TypeScript Code (snippets from my setup - please ask for further details if you need some):
```typescript
// from data access layer
export const Repository = {
  addEntryToHoloj(
    params: {
      subject: string;
      object: object;
    },
    programNumber: number
  ): Promise<void> {
    return new Promise(async (resolve, reject) => {
      SqlDataProvider.execute(
        "insert into holog.holojp values (?, ?) with NC",
        params.subject,
        JSON.stringify(params.object)
      )
        .then(() => resolve())
        .catch(reject);
    });
  },
};

// data connector
const idbPConnectionPool = new DBPool(
  {
    url: "*LOCAL",
  },
  {
    debug: true,
    incrementSize: 8,
  }
);

// from framework layer
export default class SqlDataProvider {
  public static execute<ReturnType = any>(
    sqlStatement: string,
    ...sqlParams: Array<string | number>
  ): Promise<ReturnType[]> {
    return new Promise(async (resolve, reject) => {
      idbPConnectionPool
        .prepareExecute(sqlStatement, sqlParams, {
          io: "in",
        })
        .then(resolve)
        .catch((reason) => {
          Logger.warn(reason);
          reject(reason);
        });
    });
  }
}
```

**Expected behavior**

The supplied Sql Statement should add an entry to table holog/HOLOJP.

**Additional context**
Here's some debug output from the database connection. The json error message was generated after the reject by class Logger.
You can find the actual values for the parameters in this output - I just can't find why they should have a wrong format 

```log
Finding available Connection...
Connection 0 found
Preparing Statement...
Prepare().
SQLPrepare(0): insert into holog.jwtjtp values ((select ukjwtisji from qs36f.jwtisp where isidji = ?), ?, ?) with NC
Finding available Connection...
Connection 1 found
Preparing Statement...
Prepare().
SQLPrepare(0): insert into holog.holojp values (?, ?) with NC
Binding Parameters...
Size of BoundParams: 3
 [["Demo",1,1],["fbe47aa2-bf28-4c32-a2fc-d986c31fb9bb",1,1],[1604325629,1,2]]
BindParamAsync().
Binding Parameters...
Size of BoundParams: 2
 [["Demo Errors",1,1],["{\"userName\":\"dummy\",\"deviceId\":\"dummy1\",\"logEntries\":[{\"timestamp\":\"fancytime\",\"logType\":\"fancy\",\"severity\":\"error\",\"logMessage\":\"idk what to do\"}],\"sessionId\":\"lksensaergr3\",\"apiKey\":\"kaai3on\"}",1,1]]
BindParamAsync().
SQLBindParameter(0) TYPE[ 1] SIZE[ 32] DIGI[0] IO[1] IND[ -3] INDEX[0]
SQLBindParameter(0) TYPE[ 1] SIZE[ 36] DIGI[0] IO[1] IND[ -3] INDEX[1]
SQLBindParameter(0) TYPE[ 2] SIZE[ 14] DIGI[0] IO[1] IND[  0] INDEX[2]
Execute().
SQLBindParameter(0) TYPE[ 1] SIZE[ 64] DIGI[0] IO[1] IND[ -3] INDEX[0]
SQLBindParameter(0) TYPE[14] SIZE[1048576] DIGI[0] IO[1] IND[1048576] INDEX[1]
SQLExecuteAsync(0):
SQLNUMRESULTSCOLS(0) Column Count = 0
NO RESULTS :SQLExecuteAsync()
Execute().
Fetching Result Set...
FetchAllAsync().
SQL did not return a result set.
SQLFreeStmt: stmth 3 [SQL_DROP]
SQLFreeStmt(0)
SQLExecuteAsync(-1):
Detaching Connection 1...
SQLFreeStmt: stmth 5 [SQL_DROP]
SQLFreeStmt(0)
Connection 1 detached
{"level":"warn","message":"PE: Failed to execute() statement","metadata":{"pid":818329},"stack":"Error: PE: Failed to execute() statement\n    at /node/NodeCode-HRAS/node_modules/idb-pconnector/lib/dbPool.js:271:18\n    at DBPool.prepareExecute (/node/NodeCode-HRAS/node_modules/idb-pconnector/lib/dbPool.js:269:17)\nCaused By:\n Error: SQLSTATE=22504 SQLCODE=-191 Mischbytedaten oder UTF-8-Daten haben falsches Format.\n    at Object.<anonymous> (/node/NodeCode-HRAS/node_modules/idb-pconnector/lib/statement.js:153:18)","timestamp":"2020-11-02T14:03:43.061Z"}
```

**Comment by abamara** [comment]
I have the issue since I update idb-conector from 1.2.3 to most recent version
